baseURL = "https://www.zerodaedal.us"
languageCode = "en-us"
title = "Web Design & Development for Small Business • ZeroDaedalus"
copyright = "Copyright &copy; 2024"
enableRobotsTXT = true
cleanDestinationDir = true

[build]
  [build.buildStats]
    enable = true