baseURL = "https://www.zerodaedal.us"
languageCode = "en-us"
title = "Zero Daedalus Design"
copyright = "Copyright &copy; 2024"
enableRobotsTXT = true
cleanDestinationDir = true
disableKinds = ['taxonomy', 'term']

[params] 
  description = "Affordable web design and development agency helping small businesses build and maintain successful websites."
  keywords = "website services for small business usa, WordPress design and development usa, small business web consultant usa, small business web designer usa, small business web developer usa"
  title = "Zero Daedalus Design"
  images = ["img/featured.png"]

  [params.author]
    name = "Dewitt Buckingham"
    email = "dewitt@zerodaedalus.net"

[build]
  [build.buildStats]
    enable = true


[[params.blogFilters]]
key = "design"
label = "Design"

[[params.blogFilters]]
key = "development"
label = "Development"

[[params.blogFilters]]
key = "writing"
label = "Writing"

[[params.blogFilters]]
key = "games"
label = "Games"

[[params.blogFilters]]
key = "misc"
label = "Miscellaneous"