[[main]]
name = "home"
pageRef = "/"
weight = 10
    [main.params]
        icon = "fa-wind"

[[main]]
name = "blog"
pageRef = "/blog"
weight = 20
    [main.params]
        icon = "fa-fire"

[[main]]
name = "projects"
pageRef = "/projects"
weight = 30
    [main.params]
        icon = "fa-tint"

[[main]]
name = "me"
pageRef = "/me"
weight = 40
    [main.params]
        icon = "fa-seedling"